GRANT CREATE SESSION TO app_data;
GRANT CREATE TABLE,CREATE VIEW,CREATE TRIGGER,CREATE SEQUENCE to app_data;
GRANT CREATE SESSION TO app_code;
GRANT CREATE PROCEDURE TO app_code;
GRANT CREATE SYNONYM TO app_code;

GRANT CREATE SESSION to app_admin;
GRANT CREATE PROCEDURE TO app_admin;
GRANT CREATE SYNONYM TO app_admin;

GRANT CREATE SESSION to app_user;
GRANT CREATE PROCEDURE TO app_user;
GRANT CREATE SYNONYM TO app_user;