-- app_data2
CREATE USER app_data IDENTIFIED BY "N5j3FsniqndxlwT"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;


-- app_code
CREATE USER app_code IDENTIFIED BY "z7cFqcfdC5W0o7Y"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY "Hh2bOmzhOQJBGer"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;


-- app_user
CREATE USER app_admin IDENTIFIED BY "mqZrdPF5LVtX5pj"
ENABLE EDITIONS;